version: '3'

##funciona
#services:
#  aplicacion:
#    image: external-api
#    build: .
#    ports:
#      - 8083:8080


##postgres
#services:
#  java_app2:
#    container_name: practica_video
#    image: practica:2.0.0
#    ##docker build -t practica:2.0.0 .
#    depends_on:
#      - java_db2
#    build: .
#    ports:
#      - 8083:8080
#    environment:
#      - DATABASE_URL=jdbc:postgresql://java_db2:5551/practicadb
#      - DATABASE_USERNAME=postgres
#      - DATABASE_PASSWORD=secret
#
#  java_db2:
#    container_name: db_practica_video
#    image: postgres:12
#    ports:
#      - 5551:5432
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: secret
#      POSTGRES_DB: practicadb

##MySql
services:
  java_app2:
    container_name: practica_video
    image: practica-mysql:2.0.0
    ##docker build -t practica:2.0.0 .
    depends_on:
      - java_db2
    build: .
    ports:
      - 8083:8080
    environment:
      - DATABASE_URL=jdbc:mysql://java_db2:5551/practicadb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=secrett

  java_db2:
    container_name: db_practica_video
    image: mysql:latest
    ports:
      - 5551:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: practicadb

